name: sandbox
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  provider: ^6.1.2
  easy_localization: ^3.0.7
  dio: ^5.7.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  flutter_widget_from_html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/misc/
    - assets/translations/

  fonts:
    - family: Vietnam Pro
      fonts:
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Black.ttf
          weight: 900
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Italic.ttf
          style: italic
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/static/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/static/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter-Thin.ttf
          weight: 100
